version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-dev
    ports:
      - 4000:3002
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-dev
    ports:
      - 8081:3000

  database:
    container_name: postgres
    image: postgres
    env_file: .env
    restart: unless-stopped
